name: Generate Snake

on:
  schedule:
    - cron: "0 0 * * *" # Runs every midnight
  workflow_dispatch:

jobs:
  generate:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Generate Snake
        uses: Platane/snk@v3
        with:
          github_user_name: Jolectro
          outputs: dist/snake.svg

      - name: Push Snake
        uses: EndBug/add-and-commit@v9
        with:
          message: "Generate contribution snake"
          add: "dist/snake.svg"
